package main

import (
	"flag"
	"path/filepath"

	"k8s.io/gengo/args"

	"github.com/golang/glog"
	customargs "github.com/llparse/controller-gen/args"
	"github.com/llparse/controller-gen/generators"
	"github.com/spf13/pflag"
)

var (
	name          = pflag.StringP("name", "n", "", "Name of the controller.")
	resourceTypes = pflag.StringSliceP("resource-types", "t", []string{"Node", "Pod"}, "Comma-separated list of resource types to get change events from.")
)

func main() {
	arguments := &args.GeneratorArgs{
		OutputBase:        args.DefaultSourceTree(),
		GoHeaderFilePath:  filepath.Join(args.DefaultSourceTree(), "k8s.io/kubernetes/hack/boilerplate/boilerplate.go.txt"),
		GeneratedBuildTag: "ignore_autogenerated",
		OutputPackagePath: "k8s.io/kubernetes/pkg/generated/controller",
	}
	arguments.AddFlags(pflag.CommandLine)

	flag.Set("logtostderr", "true")
	pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
	pflag.Parse()

	arguments.CustomArgs = customargs.Args{
		Name:          *name,
		ResourceTypes: *resourceTypes,
	}

	// Run it.
	if err := arguments.Execute(
		generators.NameSystems(),
		generators.DefaultNameSystem(),
		generators.Packages,
	); err != nil {
		glog.Fatalf("Error: %v", err)
	}
	glog.V(2).Info("Completed successfully.")
}
